// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcNFnEsh5kMfglSPYfrHY1r07XoJeezoE',
    appId: '1:630957314497:web:bcd0ebcaf0c12273379f40',
    messagingSenderId: '630957314497',
    projectId: 'zensort-dev',
    authDomain: 'zensort-dev.firebaseapp.com',
    storageBucket: 'zensort-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHEg2rU9hD-5XPnbLGPFoabkz7lD4ZidA',
    appId: '1:630957314497:android:776ec6b0c1f499a1379f40',
    messagingSenderId: '630957314497',
    projectId: 'zensort-dev',
    storageBucket: 'zensort-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBefGApkKryIAOgP1s_GL0-TdpPN4dGXE0',
    appId: '1:630957314497:ios:f7218e0a3f92f066379f40',
    messagingSenderId: '630957314497',
    projectId: 'zensort-dev',
    storageBucket: 'zensort-dev.firebasestorage.app',
    iosClientId:
        '630957314497-3skd8s19cr3f1juv26sduvnp4i8crtdm.apps.googleusercontent.com',
    iosBundleId: 'com.example.zensort',
  );
}
