// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcNFnEsh5kMfglSPYfrHY1r07XoJeezoE',
    appId: '1:630957314497:web:bcd0ebcaf0c12273379f40',
    messagingSenderId: '630957314497',
    projectId: 'zensort-dev',
    authDomain: 'zensort-dev.firebaseapp.com',
    storageBucket: 'zensort-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2m4TEWflZ7R0-j0YFHrOf7tvco0wv27I',
    appId: '1:286608244703:android:4e77ab474f343297e00e6a',
    messagingSenderId: '286608244703',
    projectId: 'zensort-a7b47',
    storageBucket: 'zensort-a7b47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0OwGSoqAh-JUcnu8dkfjFDf6Cxy2iFKk',
    appId: '1:286608244703:ios:fe3522dc0e715717e00e6a',
    messagingSenderId: '286608244703',
    projectId: 'zensort-a7b47',
    storageBucket: 'zensort-a7b47.firebasestorage.app',
    iosBundleId: 'com.example.zensort',
  );
}