name: Deploy to Firebase

on:
    push:
        tags:
            - 'v*' # Trigger on tags like v1.0, v1.2.3

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: 'stable'

            - name: Install dependencies
              run: flutter pub get

            - name: Make build script executable
              run: chmod +x ./scripts/build.sh

            - name: Build web application
              run: ./scripts/build.sh prod

            - name: Deploy to Firebase Hosting (Prod)
              uses: FirebaseExtended/action-hosting-deploy@v0
              env:
                  FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZENSORT_PROD }}
              with:
                  repoToken: '${{ secrets.GITHUB_TOKEN }}'
                  firebaseServiceAccount: '${{ env.FIREBASE_SERVICE_ACCOUNT }}'
                  projectId: 'zensort-a7b47'
                  channelId: 'live'
